<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIV5STVv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIV5STVv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIV5STVv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIV5STVv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIV5STVv\App_KernelDevDebugContainer([
    'container.build_hash' => 'IV5STVv',
    'container.build_id' => 'ffbb98a3',
    'container.build_time' => 1677230807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIV5STVv');
