<?php

namespace ContainerFefcStG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_H_ZqijpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.H.Zqijp' shared service.
     *
     * @return \App\Repository\ProductRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ProductController::index()": the $productRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ProductRepository".');
    }
}
