<?php

namespace ContainerIV5STVv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q4vEfg2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q4vEfg2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q4vEfg2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CartController::addToCart' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\CartController::decrease' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\CartController::removeCartAll' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\CartController::removeToCart' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.H8qgPq7', 'get_ServiceLocator_H8qgPq7Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CartController:addToCart' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\CartController:decrease' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\CartController:removeCartAll' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\CartController:removeToCart' => ['privates', '.service_locator.x0fsn2y', 'get_ServiceLocator_X0fsn2yService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.H8qgPq7', 'get_ServiceLocator_H8qgPq7Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CartController::addToCart' => '?',
            'App\\Controller\\CartController::decrease' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::removeCartAll' => '?',
            'App\\Controller\\CartController::removeToCart' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CartController:addToCart' => '?',
            'App\\Controller\\CartController:decrease' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:removeCartAll' => '?',
            'App\\Controller\\CartController:removeToCart' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
