<?php

namespace ContainerIV5STVv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H8qgPq7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H8qgPq7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H8qgPq7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productRepository' => ['privates', '.errored.H.Zqijp', NULL, 'Cannot determine controller argument for "App\\Controller\\ProductController::index()": the $productRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ProductRepository".'],
        ], [
            'productRepository' => '?',
        ]);
    }
}
