<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEeAKuMB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEeAKuMB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEeAKuMB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEeAKuMB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEeAKuMB\App_KernelDevDebugContainer([
    'container.build_hash' => 'EeAKuMB',
    'container.build_id' => '4f0cf846',
    'container.build_time' => 1677147866,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEeAKuMB');
